PREFIX lo17: <http://www.owl-ontologies.com/lo17#> 
PREFIX pf: <http://jena.hpl.hp.com/ARQ/property#>
SELECT ?titre
WHERE {
  ?lit pf:textMatch('+Création d\'une chaire' 1) .
  ?bull lo17:hasTitre ?titre .
  ?bull lo17:hasTexte ?texte .
  FILTER(?titre = ?lit || ?texte = ?lit)
}