PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl:     <http://www.w3.org/2002/07/owl#> 
PREFIX lo17:    <http://www.owl-ontologies.com/lo17#>  

SELECT DISTINCT ?titre 
WHERE {
  ?bull rdf:type lo17:Bulletin .
  ?bull lo17:hasTitre ?titre .
  FILTER regex(?titre, "CNRS", "i")
}