ALTER DATABASE sr03p036 CHARACTER SET utf8 COLLATE utf8_general_ci;

SET FOREIGN_KEY_CHECKS=0; -- to disable them

DROP TABLE IF EXISTS QQQAAANSWER CASCADE;
DROP TABLE IF EXISTS COURSE CASCADE;
DROP TABLE IF EXISTS ANSWER CASCADE;
DROP TABLE IF EXISTS QUESTION CASCADE;
DROP TABLE IF EXISTS USER CASCADE;
DROP TABLE IF EXISTS QUIZ CASCADE;

SET FOREIGN_KEY_CHECKS=1; -- to re-enable them

CREATE TABLE USER (
	email VARCHAR(150) PRIMARY KEY,
	password TEXT NOT NULL,
	name TEXT NOT NULL,
	company TEXT,
	phoneNumber TEXT,
	creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	isActive BOOLEAN DEFAULT TRUE,
	isAdmin BOOLEAN DEFAULT FALSE,
	CHECK (password > 5),
	CHECK (email LIKE '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE QUIZ (
	quiz_id INTEGER AUTO_INCREMENT PRIMARY KEY,
	subject VARCHAR(250) UNIQUE KEY,
	isActive BOOLEAN DEFAULT TRUE,
	creator VARCHAR(150) NOT NULL REFERENCES USER(email)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE QUESTION (
	question_id INTEGER AUTO_INCREMENT PRIMARY KEY,
	question VARCHAR(250) NOT NULL,
	_order INTEGER NOT NULL,
	isActive BOOLEAN DEFAULT TRUE,
	quiz INTEGER NOT NULL,
	UNIQUE KEY(question, quiz),
	UNIQUE KEY(quiz, _order),
	CONSTRAINT f_quiz FOREIGN KEY (quiz) REFERENCES QUIZ(quiz_id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE ANSWER (
	answer_id INTEGER PRIMARY KEY AUTO_INCREMENT,
	answer VARCHAR(250) NOT NULL,
	_order INTEGER NOT NULL,
	isCorrect BOOLEAN NOT NULL,
	isActive BOOLEAN DEFAULT TRUE,
	question INTEGER NOT NULL,
	UNIQUE KEY(answer, question),
	UNIQUE KEY(question, _order),
	CONSTRAINT f_question FOREIGN KEY (question) REFERENCES QUESTION(question_id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE COURSE (
	course_id INTEGER AUTO_INCREMENT PRIMARY KEY,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	duration INTEGER NOT NULL,
	score INTEGER NOT NULL,
	user VARCHAR(150) NOT NULL,
	quiz INTEGER NOT NULL REFERENCES QUIZ(quiz_id),
	UNIQUE KEY(user, quiz),
	CONSTRAINT c_user FOREIGN KEY (user) REFERENCES USER(email) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE QQQAAANSWER (
	course INTEGER NOT NULL,
	question INTEGER NOT NULL,
	answer INTEGER NOT NULL,
	PRIMARY KEY (course, question),
	CONSTRAINT FOREIGN KEY (course) REFERENCES COURSE(course_id) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (question) REFERENCES QUESTION(question_id) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (answer) REFERENCES ANSWER(answer_id) ON DELETE CASCADE
);

INSERT INTO USER(email,password,name,isAdmin) VALUES ('admin@admin.fr', 'admin', 'SuperMan', true);
INSERT INTO USER(email,password,name,isAdmin) VALUES ('reg@reg.fr', 'reg', 'Kikoulol', false);
INSERT INTO QUIZ(subject,isActive,creator) VALUES ('History',true,'admin@admin.fr');
INSERT INTO QUIZ(subject,isActive,creator) VALUES ('French',true,'admin@admin.fr');
INSERT INTO USER(email,password,name,company,phoneNumber,isAdmin) VALUES ('john@admin.fr', 'admin', 'admin', 'Google', '+123', true);
