ALTER DATABASE sr03p036 CHARACTER SET utf8 COLLATE utf8_general_ci;

SET FOREIGN_KEY_CHECKS=0; -- to disable them

DROP TABLE IF EXISTS ANNONCE CASCADE;
DROP TABLE IF EXISTS ADRESSE CASCADE;
DROP TABLE IF EXISTS CATEGORIE CASCADE;

SET FOREIGN_KEY_CHECKS=1; -- to re-enable them

CREATE TABLE CATEGORIE (
	categorie_id INTEGER AUTO_INCREMENT PRIMARY KEY,
	nom VARCHAR(255) NOT NULL UNIQUE
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE ADRESSE (
	adresse_id INTEGER AUTO_INCREMENT PRIMARY KEY,
	rue VARCHAR(255) NOT NULL,
	ville VARCHAR(255) NOT NULL,
	codepostal VARCHAR(7) NOT NULL/*,
	UNIQUE KEY(rue, ville, codepostal)*/
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE ANNONCE (
	annonce_id INTEGER AUTO_INCREMENT PRIMARY KEY,
	nom VARCHAR(255) NOT NULL,
	categorie_id INTEGER NOT NULL,
	adresse_id INTEGER NOT NULL,
	telephone VARCHAR(7) NOT NULL,
	UNIQUE KEY(nom, categorie_id, telephone),
	CONSTRAINT abc FOREIGN KEY (categorie_id) REFERENCES CATEGORIE(categorie_id) ON DELETE CASCADE,
	CONSTRAINT def FOREIGN KEY (adresse_id) REFERENCES ADRESSE(adresse_id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
